package ca.mktsk.modsenfree.io

object PatcherMessage extends Enumeration {
  type Message = Value
  val PATCH_SUCCESS,
  UNPATCH_SUCCESS,
  IS_PATCHED_TRUE,
  IS_PATCHED_FALSE,
  IS_PATCHED_CHECK_ERROR,
  ERROR,
  MISSING_GAME_ASSEMBLY_ERROR,
  MISSING_PATCH_ASSEMBLY_ERROR,
  MISSING_ASSEMBLY_ERROR,
  ASSEMBLY_READ_ERROR,
  GAME_ASSEMBLY_READ_ERROR,
  GAME_ASSEMBLY_BACKUP_ERROR,
  PATCH_ASSEMBLY_READ_ERROR,
  INJECTION_ERROR,
  REPEAT_OPERATION_ERROR,
  INVALID_COMMAND_ERROR,
  TOO_FEW_ARGUMENTS_ERROR,
  UNIMPLEMENTED_ERROR = Value
}
